dist: bionic
sudo: required

language: cpp

os:
    - linux

compiler:
    - gcc

stages:
  - compile
  - test

jobs:
  include:
    - stage: compile
      name: "compilation"
      install:
        - source ci/travis/install-linux.sh
      script:
        - make app
    - stage: "Tests"
      name: "Unit Tests"
      install:
        - source ci/travis/install-linux.sh
      script: 
        - make test
        - ./test
