dist: bionic

language: cpp

os:
    - linux

compiler:
    - gcc

stages:
  - uncrustify
  - check
  - compile
  - test

jobs:
  include:
    - stage: uncrustify
      name: "Check code style"
      install:
        - sudo apt install -qq uncrustify
      script:
        - find . -name "*.cpp" > files.txt
        - find . -name "*.h" >> files.txt
        - uncrustify -c uncrustify.cfg -F files.txt --check || echo "failed to uncrustify"
    - stage: check
      name: "Static analysis"
      install:
        - source ci/travis/install-linux.sh
      script:
        - cd $TRAVIS_BUILD_DIR
        - cppcheck -q --enable=all --std=c++11 --std=posix --suppress=missingIncludeSystem .
        - scan-build -o ./result --status-bugs -analyze-headers make app
    - stage: compile
      name: "compilation"
      install:
        - source ci/travis/install-linux.sh
      script:
        - cd $TRAVIS_BUILD_DIR
        - make app
    - stage: "Tests"
      name: "Unit Tests"
      install:
        - source ci/travis/install-linux.sh
      script:
        - cd $TRAVIS_BUILD_DIR
        - make test_app
        - ./test_app
