dist: bionic
sudo: required

language: cpp

os:
    - linux

compiler:
    - gcc

stages:
  - check
  - compile
  - test

jobs:
  include:
    - stage: check
      name: "Static analysis"
      install:
        - source ci/travis/install-linux.sh
      script:
        - cd $TRAVIS_BUILD_DIR
        - cppcheck -q --enable=all --std=c++11 --std=posix --suppress=missingIncludeSystem .
        - scan-build -o ./result --status-bugs -analyze-headers make app
    - stage: compile
      name: "compilation"
      install:
        - source ci/travis/install-linux.sh
      script:
        - cd $TRAVIS_BUILD_DIR
        - make app
    - stage: "Tests"
      name: "Unit Tests"
      install:
        - source ci/travis/install-linux.sh
      script:
        - cd $TRAVIS_BUILD_DIR
        - make test_app
        - ./test_app
